---
language: python
python: "2.7"

# Use the new container infrastructure
dist: trusty
sudo: false

install:
  # Install ansible, ansible-lint and ansible-review
  - pip install ansible
  - pip install ansible-review

  # Create ansible.cfg with correct roles_path and local_tmp
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'local_tmp = ~/.ansible/tmp'; } >> ansible.cfg"

  # Check ansible,  version
  - ansible --version
  - ansible-lint --version
  - ansible-review --version

script:
  # Continuous integration: syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check -vvv

  # Continous integration: ansible-list
  - ansible-lint -p *yml

  #  Continous integration: ansible code review
  #- git ls-files *yml roles/ vars/ tests/  | xargs ansible-review

  # Continouse integration: ansible code review of changes between master and current branch
  #- git diff master | ansible-review


#notifications:
#  webhooks:
