# roles/calibre/tasks/main.yml requires calibre_via_debs (to be True) before calling this script.

# MOVED UP TO roles/calibre/tasks/main.yml
#- name: Start by installing OS's Calibre package
#  package:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - calibre
#    - calibre-bin
#  when: internet_available

# April/May 2018: Raspbian .deb's for the latest Calibre now appear
# (http://raspbian.raspberrypi.org/raspbian/pool/main/c/calibre/)
# within about 10 days of Calibre's quasi-monthly releases
# (https://calibre-ebook.com/whats-new).

# If you want the latest Calibre, run the appropriate below script, standalone.
# HOWEVER: it's strongly suggested you wait for apt (blessed by your OS!)

#- name: Install packages that Raspbian .deb's had installed for Calibre 3.23 (rpi)
#  #command: scripts/calibre-install-latest-rpi.sh  # FAILS with Calibre 3.24+ ("calibre : Depends: python-pyqt5 (>= 5.10.1+dfsg-2) but 5.10.1+dfsg-1+rpi1 is to be installed") since June 2018.
#  command: scripts/calibre-install-packages.sh     # BORROWED package list from /var/log/apt/history.log (that resulted from 2018-05-22 install of Calibre 3.23 using calibre-install-latest-rpi.sh).
#  when: is_rpi and internet_available

#- name: Upgrade to latest Calibre using Debian's own .deb's from testing (rpi)
#  command: scripts/calibre-install-latest.sh       # NECESSARY since Calibre 3.24 (BEWARE installing libc6 will prevent boot in RPi Zero W, i.e. if calibre-install-packages.sh isn't run above!)
#  when: is_rpi and internet_available

#- name: Upgrade to latest Calibre using .deb's from testing (rpi)
#  #command: scripts/calibre-install-latest-rpi-plus.sh    # WORKS for Calibre 3.27.1 on 2018-07-22 (#948 -> PR #950) THO NOT BOOTABLE IN Zero W (#952).  Similar to Calibre 3.24.x & 3.25 in June 2018, which had used calibre-install-packages.sh then Debian's own calibre-install-latest.sh
#  #command: scripts/calibre-install-latest-rpi.sh    # WORKS for Calibre 3.28 on 2018-07-26 (PR #971).  Likewise for Calibre 3.26.x
#  command: scripts/calibre-install-latest.sh    # REQUIRED for Calibre 3.29 on 2018-08-21 (PR #1015), as all above strategies failed (only script that was not attempted: Sid-like calibre-install-unstable.sh).  CLARIF: RESULTING microSD's ARE NOT BOOTABLE IN Zero W (#952)
#  when: is_rpi and internet_available

- name: Download PINNED version {{ calibre_deb_pin_version }} of calibre & calibre-bin (rpi)
  get_url:
    url: "{{ calibre_deb_url }}/{{ item }}"
    dest: "{{ downloads_dir }}/{{ item }}"
    mode: 0644
    #force: no
    #backup: no
    timeout: "{{ download_timeout }}"
  with_items:
    - calibre_{{ calibre_deb_pin_version }}_all.deb
    - calibre-bin_{{ calibre_bin_deb_pin_version }}_armhf.deb
  when: is_rpi and internet_available

- name: Install/Upgrade both, to PINNED version {{ calibre_deb_pin_version }} while using additional .deb's from testing (rpi)
  command: scripts/calibre-install-pinned-rpi.sh    # RECOMMENDED for Calibre 3.30 on 2018-08-30, so IIAB microSD will be bootable in RPi Zero W
  when: is_rpi and internet_available

- name: Install/Upgrade to Calibre testing .deb's - target Ubuntu 16.04 (not rpi and not ubuntu_18)
  command: scripts/calibre-install-latest.sh
  when: not is_rpi and not is_ubuntu_18 and internet_available

- name: Install/Upgrade to Calibre unstable .deb's IF calibre_unstable_debs
  command: scripts/calibre-install-unstable.sh
  when: calibre_unstable_debs and internet_available
